Update sonar-analysis.yml

diff --git a/.github/workflows/sonar-analysis.yml b/.github/workflows/sonar-analysis.yml
--- a/.github/workflows/sonar-analysis.yml
+++ b/.github/workflows/sonar-analysis.yml
@@ -21,6 +21,12 @@ jobs:
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 6.0.419
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'zulu' # Alternative distribution options are available.
           
       - name: Checkout code
         uses: actions/checkout@v2
@@ -60,3 +66,11 @@ jobs:
           dotnet build src/TechLanches/TechLanches.sln --configuration Release
           dotnet test test/**/*.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
           ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+          
+      - name: Check Quality Gate status
+        run: |
+          STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=g12-4soat_techlanches-app" | jq -r '.projectStatus.status')
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Aborting workflow."
+            exit 1
+          fi
